name: build
on:
  push:
    branches: [ 💥 ]
    tags:
      - 'v*'

env:
  zig-version: 0.7.1

jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, i386]
        mode: [ReleaseSafe, ReleaseFast, ReleaseSmall, Debug]
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - name: Setup basic environment
        run: apk add git musl-dev
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: goto-bus-stop/setup-zig@1.3.0
        with:
          version: ${{ env.zig-version }}
      - name: Build on linux
        run: |
          zig build -Dtarget=${{ matrix.arch }}-linux-musl -Dmode=${{ matrix.mode }} --verbose
          zig build bootstrap -Dtarget=${{ matrix.arch }}-linux-musl -Dmode=${{ matrix.mode }} --verbose
      - uses: actions/upload-artifact@v2
        with:
          name: bin-linux-${{ matrix.arch }}-${{ matrix.mode }}
          path: zig-cache/bin
  build-windows:
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, i386]
        mode: [ReleaseFast, ReleaseSmall, Debug]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: codehz/setup-zig@v1.2.8
        with:
          version: ${{ env.zig-version }}
      - name: Download rcedit.exe
        uses: robinraju/release-downloader@v1
        with:
          repository: electron/rcedit
          latest: true
          fileName: rcedit-x64.exe
          out-file-path: ${{ runner.tool_cache }}/rcedit
      - name: Setup rcedit
        run: |
          Rename-Item ${{ runner.tool_cache }}\rcedit\rcedit-x64.exe ${{ runner.tool_cache }}\rcedit\rcedit.exe
          echo "${{ runner.tool_cache }}\rcedit" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Build on windows
        run: |
          zig build -Dtarget=${{ matrix.arch }}-windows-gnu -Dmode=${{ matrix.mode }} -Dextra=false --verbose
          zig build bootstrap -Dtarget=${{ matrix.arch }}-windows-gnu -Dmode=${{ matrix.mode }} -Dextra=false --verbose
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: bin-windows-${{ matrix.arch }}-${{ matrix.mode }}
          path: zig-cache/bin
  package-extra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge folders
        run: cp -RT extra/inf/ extra/win32/
      - name: Upload extra
        uses: actions/upload-artifact@v2
        with:
          name: extra-windows
          path: extra/win32
  create-release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows, package-extra]
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v2
      - name: List folders
        run: |
          for win in bin-windows-*; do
            cp -r extra-windows/* $win
          done
          rm -rf extra-windows
          for dir in bin-*; do
            mv $dir ${dir/bin-/}
          done
          files=(*)
          echo "files=${files[@]}" | tee -a $GITHUB_ENV
          echo "time=x$(date +%s)" | tee -a $GITHUB_ENV
      - name: Tag snapshot
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.time }}
      - uses: meeDamian/github-release@2.0
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          tag: ${{ env.time }}
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ${{ env.files }}
      - uses: meeDamian/github-release@2.0
        if: "startsWith(github.ref, 'refs/tags/')"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ${{ env.files }}
          draft: true
