name: build
on:
  push:
    branches: [ 💥 ]

env:
  zig-version: 0.6.0+4b48fccad

jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, i386]
        mode: [ReleaseSafe, ReleaseFast, ReleaseSmall, Debug]
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - name: Setup basic environment
        run: apk add git musl-dev
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: codehz/setup-zig@v1.2.8
        with:
          version: ${{ env.zig-version }}
      - name: Build on linux
        run: |
          zig build -Dtarget=${{ matrix.arch }}-linux-musl -Dmode=${{ matrix.mode }} --verbose
          zig build bootstrap -Dtarget=${{ matrix.arch }}-linux-musl -Dmode=${{ matrix.mode }} --verbose
      - uses: actions/upload-artifact@v2
        with:
          name: bin-${{ matrix.arch }}-${{ runner.os }}-${{ matrix.mode }}
          path: zig-cache/bin
  build-windows:
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, i386]
        mode: [ReleaseFast, ReleaseSmall, Debug]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: codehz/setup-zig@v1.2.8
        with:
          version: ${{ env.zig-version }}
      - name: Download rcedit.exe
        uses: robinraju/release-downloader@v1
        with:
          repository: electron/rcedit
          latest: true
          fileName: rcedit-x64.exe
          out-file-path: ${{ runner.tool_cache }}/rcedit
      - name: Setup rcedit
        run: |
          Rename-Item ${{ runner.tool_cache }}\rcedit\rcedit-x64.exe ${{ runner.tool_cache }}\rcedit\rcedit.exe
          echo "${{ runner.tool_cache }}\rcedit" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Build on windows
        run: |
          zig build -Dtarget=${{ matrix.arch }}-windows-gnu -Dmode=${{ matrix.mode }} --verbose
          zig build bootstrap -Dtarget=${{ matrix.arch }}-windows-gnu -Dmode=${{ matrix.mode }} --verbose
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: bin-${{ matrix.arch }}-${{ runner.os }}-${{ matrix.mode }}
          path: zig-cache/bin
  package-extra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge folders
        run: cp -RT extra/inf/ extra/win32/
      - name: Upload extra
        uses: actions/upload-artifact@v2
        with:
          name: extra-windows
          path: extra/win32
